### PR TITLE
Fix(camel_case): Fixed First character not Uppercase after 2nd word onwards

### PR DESCRIPTION
**Pull request by agadev**
Fixed First character not Uppercase after 2nd word onwards

### CODE REVIEW

**Comment by rknell** [comment]
Hey Agadev,

In this case I probably wont accept the commit as it would be a breaking change. I often use the library and prefer it returning sentence case. I understand that you want word case and if we are going to go with this feature I would probably add an optional name param like "toCase": Capitalization.sentence (where Capitalization is an enum)

If you want to submit a pull request for that great, but I understand if you will just implement it locally.

Also note that you can run the preflight checks with the script in the root of the project directory to be sure everything passes.

Cheers,

Ryan

**Comment by rknell** [comment]
I am closing for now, happy to reopen if you want to change the implementation or discuss further.

**Comment by agadev** [comment]
@rknell Thanks for quick reply. I will try to submit new PR as per your suggestions.

**Comment by rknell** [comment]
No worries. In the meantime I remembered this library I have used successfully in the past to get you going:
https://pub.dev/packages/recase

**Pull request closed without merging**
