### PR TITLE
Add useful indexOf() method

### PR DESCRIPTION
**Pull request by annorax**

### CODE REVIEW

**Comment by rknell** [comment]
Hello,

Happy to add the indexOf method, but before I can merge it in can you please ensure it passes the Travis checks?

**Comment by annorax** [comment]
> Hello,
> 
> Happy to add the indexOf method, but before I can merge it in can you please ensure it passes the Travis checks?

There was a bug, which I fixed, and added a test, but now it's still failing dues to some formatting problem, which I can't figure out. I am unfamiliar with this check.

**Comment by rknell** [comment]
Sure, if you run `dartfmt .` in the root of the project it will ensure the files whitespace etc are formatted correctly. This is in place to ensure merging is easy if someone else is working on a pull request - and also to ensure the next person doesn't do a dart format and we can see exactly what they changed.

The docs for dartfmt are here (https://dart.dev/tools/dartfmt), or let me know if you are still stuck

**Review by rknell — APPROVED** [review]
Changes look good

**Pull request merged**
